# https://eslint.org/docs/user-guide/configuring
---
  root: true
  parser: vue-eslint-parser
  parserOptions:
    parser: babel-eslint
  extends:
    - prettier
    - plugin:vue/essential
  rules:
    no-unused-vars:
      - warn
